CREATE TABLE IF NOT EXISTS "dailyStatsLanding" (
    "id" uuid DEFAULT uuid_generate_v4(),
     "playerName" text NOT NULL,
     "position" varchar(10) NOT NULL,
     "age" int NOT NULL,
     "team" varchar(10) NOT NULL,
     "gamesPlayed" int NOT NULL,
     "gamesStarted" int NOT NULL,
     "minutesPlayed" int NOT NULL,
     "fieldGoals" int NOT NULL,
     "fieldGoalAttempts" int NOT NULL,
     "fieldGoalPercentage" decimal(3, 1) NOT NULL,
     "threePointFieldGoals" int NOT NULL,
     "threePointFieldGoalAttempts" int NOT NULL,
     "threePointFieldGoalPercentage" decimal(3, 1) NOT NULL,
     "twoPointFieldGoals" int NOT NULL,
     "twoPointFieldGoalAttempts" int NOT NULL,
     "twoPointFieldGoalPercentage" decimal(3, 1) NOT NULL,
     "effectiveFieldGoalPercentage" decimal(3, 1) NOT NULL,
     "freeThrows" int NOT NULL,
     "freeThrowAttempts" int NOT NULL,
     "freeThrowPercentage" decimal(3, 1) NOT NULL,
     "offensiveRebounds" int NOT NULL,
     "defensiveRebounds" int NOT NULL,
     "totalRebounds" int NOT NULL,
     "assists" int NOT NULL,
     "steals" int NOT NULL,
     "blocks" int NOT NULL,
     "turnovers" int NOT NULL,
     "personalFouls" int NOT NULL,
     "points" int NOT NULL
);
