CREATE TABLE IF NOT EXISTS "dailyStatsLanding" (
     "id" uuid DEFAULT uuid_generate_v4(),
     "playerName" text NOT NULL,
     "position" varchar(10),
     "age" int,
     "team" varchar(10),
     "gamesPlayed" int,
     "gamesStarted" int,
     "minutesPlayed" int,
     "fieldGoals" int,
     "fieldGoalAttempts" int,
     "fieldGoalPercentage" decimal(3, 1),
     "threePointFieldGoals" int,
     "threePointFieldGoalAttempts" int,
     "threePointFieldGoalPercentage" decimal(3, 1),
     "twoPointFieldGoals" int,
     "twoPointFieldGoalAttempts" int,
     "twoPointFieldGoalPercentage" decimal(3, 1),
     "effectiveFieldGoalPercentage" decimal(3, 1),
     "freeThrows" int,
     "freeThrowAttempts" int,
     "freeThrowPercentage" decimal(3, 1),
     "offensiveRebounds" int,
     "defensiveRebounds" int,
     "totalRebounds" int,
     "assists" int,
     "steals" int,
     "blocks" int,
     "turnovers" int,
     "personalFouls" int,
     "points" int,
     "datetimePulled" timestamp NOT NULL
);
